[project]
name = "klinikatlas-search"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Pia Baronetzky", email = "pia@baronetzky.org" }
]
requires-python = ">=3.10"
dependencies = [
    "de-klinikatlas",
    "httpx>=0.28.1",
    "ipywidgets>=8.1.9",
    "jupyter>=1.1.1",
    "notebook>=7.6.2",
    "numpy>=2.2.6",
    "openpyxl>=3.1.5",
    "pandas>=2.3.3",
    "requests>=2.34.2",
    "safetensors>=0.8.0",
    "torch==2.11.0",
    "tqdm>=4.70.0",
    "transformers>=5.16.1",
]

[project.scripts]
klinikatlas-search = "klinikatlas_search:main"

[build-system]
requires = ["uv_build>=0.12.9,<0.13.0"]
build-backend = "uv_build"

[tool.uv.sources]
de-klinikatlas = { git = "https://github.com/bundesAPI/klinikatlas-api.git", subdirectory = "python-client" }

[dependency-groups]
dev = [
    "ipykernel>=7.3.0",
]
